import {
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  BarChart2,
  BarChart3,
  Bell,
  Bug,
  Building2,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  EllipsisVertical,
  Circle,
  CircleAlert,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Code,
  Copy,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileSpreadsheet,
  FileText,
  Flag,
  Folder,
  GraduationCap,
  GitBranch,
  GitPullRequest,
  Globe,
  Kanban,
  KeyRound,
  Layers,
  Lock,
  LogOut,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListChecks,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  Phone,
  Plug,
  Monitor,
  Moon,
  Network,
  Package,
  Inbox,
  Truck,
  UtensilsCrossed,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ShoppingCart,
  Briefcase,
  Landmark,
  Sparkles,
  SlidersHorizontal,
  Shield,
  ShieldCheck,
  Square,
  Star,
  Sun,
  SunMedium,
  Target,
  TestTube,
  Timer,
  Trash2,
  TrendingUp,
  Upload,
  UserPlus,
  Users,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

export const AppIcon = ({ icon: Icon, size = 16, strokeWidth = 2, className = '', ...props }) => {
  if (!Icon) return null;
  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      className={className ? `app-icon ${className}` : 'app-icon'}
      aria-hidden={props['aria-label'] ? undefined : true}
      {...props}
    />
  );
};

export const Icons = {
  logo: Layers,
  sparkles: Sparkles,
  folder: Folder,
  layoutGrid: LayoutGrid,
  kanban: Kanban,
  list: List,
  listChecks: ListChecks,
  logOut: LogOut,
  bell: Bell,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moreVertical: EllipsisVertical,
  plus: Plus,
  x: X,
  menu: Menu,
  moon: Moon,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  sun: Sun,
  search: Search,
  send: Send,
  cart: ShoppingCart,
  package: Package,
  inbox: Inbox,
  truck: Truck,
  utensils: UtensilsCrossed,
  building: Building2,
  briefcase: Briefcase,
  userStar: Star,
  messageSquare: MessageSquare,
  arrowLeftRight: ArrowLeftRight,
  circle: Circle,
  circleAlert: CircleAlert,
  download: Download,
  externalLink: ExternalLink,
  alertTriangle: AlertTriangle,
  bug: Bug,
  calendarDays: CalendarDays,
  calendarPlus: CalendarPlus,
  sliders: SlidersHorizontal,
  timer: Timer,
  trendingUp: TrendingUp,
  check: Check,
  clipboardCheck: ClipboardCheck,
  refreshCw: RefreshCw,
  barChart3: BarChart3,
  barChart: BarChart2,
  arrowRight: ArrowRight,
  play: Play,
  square: Square,
  star: Star,
  clock: Clock,
  keyRound: KeyRound,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  mail: Mail,
  mapPin: MapPin,
  monitor: Monitor,
  pencil: Pencil,
  phone: Phone,
  trash: Trash2,
  upload: Upload,
  users: Users,
  wrench: Wrench,
  copy: Copy,
  eye: Eye,
  eyeOff: EyeOff,
  checkCircle: CheckCircle2,
  checkCheck: CheckCheck,
  userPlus: UserPlus,
  flag: Flag,
  graduationCap: GraduationCap,
  layoutDashboard: LayoutDashboard,
  lock: Lock,
  shield: Shield,
  shieldCheck: ShieldCheck,
  rocket: Rocket,
  code: Code,
  layers: Layers,
  gitBranch: GitBranch,
  dollar: DollarSign,
  network: Network,
  plug: Plug,
  target: Target,
  map: Map,
  globe: Globe,
  clipboard: ClipboardList,
  refresh: RefreshCw,
  landmark: Landmark,
};

/** Resolve a catalog icon key to a Lucide component. */
export function resolveIcon(name) {
  if (!name) return Icons.layers;
  return Icons[name] ?? Icons.layers;
}

export const ENV_ICONS = {
  Development: Code,
  Staging: Layers,
  UAT: ShieldCheck,
  Production: Rocket,
};

export function IconButton({ icon, label, variant = 'default', size = 15, className = '', ...props }) {
  const cn = `icon-btn${variant === 'danger' ? ' icon-btn-danger' : ''}${variant === 'success' ? ' icon-btn-success' : ''}${className ? ` ${className}` : ''}`;
  return (
    <button type="button" className={cn} title={label} aria-label={label} {...props}>
      <AppIcon icon={icon} size={size} />
    </button>
  );
}

export const PROJECT_SECTION_ICONS = {
  dashboard: LayoutDashboard,
  members: Users,
  'project-team': Users,
  backlog: List,
  sprint: Zap,
  scrum: Clock,
  scope: FileText,
  bugs: Bug,
  testing: ClipboardCheck,
  deploy: Code,
  credentials: KeyRound,
  maint: Wrench,
  calendar: CalendarDays,
  reports: BarChart3,
  time: Clock,
};

export const NOTIFICATION_ICONS = {
  pr: GitPullRequest,
  bug: Bug,
  sprint: Zap,
  deploy: Rocket,
  task: CheckCircle2,
  default: Megaphone,
};

export const CEREMONY_ICONS = {
  planning: Calendar,
  standup: SunMedium,
  review: Search,
  retro: RefreshCw,
  grooming: ClipboardList,
  stakeholder: BarChart2,
};

export const SDLC_ICONS = {
  Planning: ClipboardList,
  Design: Palette,
  Development: Monitor,
  Testing: TestTube,
  Deployment: Rocket,
  Maintenance: Wrench,
};
